name: Issue Auto Comment

on:
  issues:
    types: [opened, labeled]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment for bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "Thank you. We will fix it."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment for feature label
        if: contains(github.event.issue.labels.*.name, 'feature')
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "Thank you, we will consider to include this feature."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment for discussion label
        if: contains(github.event.issue.labels.*.name, 'discussion')
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "Thanks for starting this discussion! We welcome community input."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
